### ISSUE TITLE
Building the Examples using  NDA libs

### ISSUE THREAD

**Issue by ChristophLGDV** [sensics/OSVR-RenderManager#40] opened 2016-03-02 12:06 UTC
HI,

I want to compile the examples using direct-mode libraries.

by now I have a solution for the "osvrRenderManager0.6.38" that is missing the renderkit sources and the rendermanager project from this page, which uses vrpn and thus no direct mode.

It was hinted at that I can compile from source and copy the precompiled binaries.

Can someone please provide a short overview what to build and what to copy where?

Best Regards

**Comment by russell-taylor** [comment] 2016-03-02 14:47
The RenderManager installer (0.6.39 is the current version, but 0.6.38 will do fine) installs the header and library files to link the example programs (or your own programs) and use RenderManager on 64-bit Windows.  These were built against the DirectMode libraries from nVidia and AMD (which are under NDA and so cannot be released as open source).

For those who have access to the NDA source, it is possible to pull and compile the DirectMode library from the source page.  Otherwise, it is still possible to pull and compile the non-NDA portions.  Both versions have exactly the same API and interface, but one does not implement DirectMode when it is set in the configuration file.

If the non-NDA version is compiled from the same version of the source that was used to compile the installer (the 0.6.39 is up to date with master as of today), then the osvrRenderManager.dll file from the installer can be copied over and used, providing the DirectMode interfaces.  However, you could also have compiled against the installer's header and library directly and avoided compiling the source code for RenderManager entirely.

p.s. Both the DirectMode and non-DirectMode versions use VRPN.  The issue is whether they have access to the code under NDA from nVidia and AMD.

**Closed by russell-taylor** 2016-03-02 14:47 UTC
