### ISSUE TITLE
Center-of-Projection (COP) handling is wrong in UnrealEngine4 (or RenderManager) with our custom HMD

### ISSUE THREAD

**Issue by ccll** [sensics/OSVR-RenderManager#79] opened 2016-04-28 13:24 UTC
Our team have been playing with OSVR-Unreal integration for 2 days, and encountered an significant issue where the rendered stereo images do not align in our HMD, the same object in left eye and right eye are too far away to create a combined stereoscopic view.
The same issue actually appeared when we're evaluating OSVR-Unity the first time, after we adjusted the `center_proj_x` setting to 0.6/0.4 according to the specs of our HMD, the views align perfectly.
![vrgatecop](https://cloud.githubusercontent.com/assets/5366582/14886070/7572428c-0d81-11e6-9ae5-6b9131b522ba.png)

Now with the same settings, they do not align any more in OSVR-Unreal, so I started messing with some parameters and capture the output from both Unity3D and UE4, and found out the difference.

Firstly let's set the distortion to identity and set `center_proj_x` to a extremely biased value (for example 0.8/0.2).
![withoutdistortion](https://cloud.githubusercontent.com/assets/5366582/14886202/33b07408-0d82-11e6-991d-0270f15b4f18.png)
Output from Unity3D:
![unity](https://cloud.githubusercontent.com/assets/5366582/14886259/7afcc78a-0d82-11e6-8aa4-59aa1c3d8e2f.png)
Output from UE4:
![ue4](https://cloud.githubusercontent.com/assets/5366582/14886266/82f76d14-0d82-11e6-9d84-e8a51bd7c7f5.png)

It's not very obvious what's wrong, let's add some odd distortion to visualize the 'center of projection'.
![distortionparams](https://cloud.githubusercontent.com/assets/5366582/14886313/c045181a-0d82-11e6-9fa0-1e0b378f9c78.png)
Output from Unity3D: (you can see that when we put the boxes at the COP in left eye, the same boxes also appear at the COP in right eye, this is perfectly aligned to someone with a super-narrow IPD :)
![unitydistorted](https://cloud.githubusercontent.com/assets/5366582/14886330/d58f5a6e-0d82-11e6-8ba9-0cda8383f7ac.png)
Output from UE4: (when boxes is put at the COP in left eye, the same boxes is way off in right eye)
![ue4distorted](https://cloud.githubusercontent.com/assets/5366582/14886334/dc6e50d8-0d82-11e6-942b-beaa18f8e32f.png)

I hope this may give some lead.

P.S. Later I messed around with OSVR-Oculus-Rift plugin and a DK2, no matter what value is given to `center_proj_x`, the output looks great in UE4 (but unaligned in Unity3D unless `center_proj_x` is set to 0.5/0.5), I suppose it's because the actual physical COP of DK2 is exactly 0.5/0.5 where the output of OSVR-Unreal perfectly matches this metric. And another question arises, I see that HDK 1.3 is using a 0.471/0.529 COP setting from the sample config, so does it look correct in UE4?

**Comment by JeroMiya** [comment] 2016-04-28 14:52
There is a fix in the works for the projection code to use the overfill-adjusted projections from RenderManager. In the meantime, could you set your renderOverfillFactor to 1.0 in your renderManagerConfig and see if that improves your center of projection? It still won't be exactly right (the RM projection and the OSVR-Core projection clipping planes are still slightly different even with renderOverFillFactor of 1.0), but it should be closer.

If it's still off, let us know.

**Comment by ccll** [comment] 2016-04-29 02:04
@JeroMiya Thanks for the tip, I've tried your solution but unfortunately it's still off.
OverfillFactor 1.5:
![ue4-overfill-1_5](https://cloud.githubusercontent.com/assets/5366582/14906729/882d6620-0df1-11e6-8945-6cbda025a04e.png)
OverfillFactor 1.0:
![ue4-overfill-1_0](https://cloud.githubusercontent.com/assets/5366582/14906730/8d5b07f6-0df1-11e6-8e0d-1066c6207eb4.png)

**Comment by russell-taylor** [comment] 2016-05-02 20:36
See https://github.com/OSVR/OSVR-Docs/blob/master/Configuring/projectionAndViewMatrices.md for a description of the OSVR RenderManager transformations, with details of the meanings for center of projection, fields of view, overlap percentage and so forth in https://github.com/OSVR/OSVR-Docs/blob/master/Configuring/distortion.md and to see how to programmatically set them from a new HMD along with distortion correction, https://github.com/OSVR/distortionizer/blob/master/angles_to_config/doc/anglesToConfig.md

**Comment by russell-taylor** [comment] 2016-05-02 20:38
It is correct that the DK2 has its eyes centered on the halfs of the screen, so has 0.5 as its X COP.  The OSVR HDK has slightly offset centers of projection, as reflected in the different offsets.

**Comment by ccll** [comment] 2016-05-03 03:02
@russell-taylor Thanks for the guides, I thought I've read these thoroughly and fully understanding what the COP means, I'll read these again to ensure nothing is missed, but for now I still suppose the problem is not on our side, because in UE4 `center_proj_x` only changed 'the center of the radial distortion', while in Unity3D it changed both 'the center of the radial distortion' and 'the center of the rendered image', and our HMD looks correct in Unity3D.

Meanwhile I've accidentally found out that when our display resolution is set to 1920x1080 as the same as DK2, the views align correctly in UE4, but in full resolution 2560x1440 views do not align and looks far apart just as I reported previously, hope this can give some lead.

**Comment by russell-taylor** [comment] 2016-05-04 13:35
Glad to hear that you had already found the docs.  As Jeremy said, there is a fix in the works for UE4 that uses the RenderManager projection matrices that should help on that platform.

**Comment by JeroMiya** [comment] 2016-05-04 13:47
It should already be merged into master.

**Comment by ccll** [comment] 2016-05-05 02:02
@JeroMiya Nice to know that! Is there a pre-built binary package to download?

**Comment by ccll** [comment] 2016-05-05 07:13
@JeroMiya Nice to hear that! I would like to known when will this be included in the pre-compiled binaries.

**Comment by ccll** [comment] 2016-05-23 08:28
@russell-taylor @JeroMiya I've updated both OSVR-Runtime and OSVR-Unreal to the latest version, OSVR-Runtime to v0.6-1194-g0c54f5e, OSVR-Unreal to [b60d5d](https://github.com/OSVR/OSVR-Unreal/commit/b60d5d452d0663b0a1c01bbce6229f879b7d4596), and still no luck.
I suppose the 'projection matrices fix' you mentioned is in commit [0f51e9](https://github.com/OSVR/OSVR-Unreal/commit/0f51e9edbc6770cc2f8261d76208cf77a5b3ba0f), unfortunately after this commit the left and right eye looks even further away in HMD.

**Comment by russell-taylor** [comment] 2016-05-23 15:18
If things are working for you in the RenderManager example programs and Unity, then it looks like we need to take another look at the Unreal plug-in to see what is going on.  If it fails in all three, we'll need to take another look at RenderManager and/or how the configuration files match the HMD.

**Comment by ccll** [comment] 2016-05-24 02:03
@russell-taylor Just confirmed again, it's **PERFECT** in both the RenderManager example and Unity, the issue only appears in Unreal.

**Comment by russell-taylor** [comment] 2016-06-08 20:30
We're looking into this with the HDK 2.0, which reproduces the problem.  Testing with a current build of and Unreal demo.  Failing that, we'll take a look at the following:

[4:25 PM] Jeremy Bell: here is where the projection is calculated: https://github.com/OSVR/OSVR-Unreal/blob/rel-ue-4.12/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRHMDDescription.cpp#L255 which we call from here: https://github.com/OSVR/OSVR-Unreal/blob/rel-ue-4.12/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRHMD.cpp#L650
[4:26 PM] Jeremy Bell: And this is where we get the projection clipping planes from render manager: https://github.com/OSVR/OSVR-Unreal/blob/rel-ue-4.12/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRCustomPresentD3D11.h#L164

**Comment by russell-taylor** [comment] 2016-06-24 16:49
We've gotten this fixed in the latest master of RenderManager, and it has been tested in the latest Unreal. We replaced the projection transforms used by the Unreal plug-in with ones that work in this case.

**Comment by JeroMiya** [comment] 2016-06-24 20:07
@russell-taylor have we actually tested with the above configuration from @ccll? Also the OSVR-Unreal branch that uses the new API isn't merged yet.

**Comment by ccll** [comment] 2016-06-27 10:02
@russell-taylor I've sent you an email (russ@reliasolve.com) with our HMD config json attached, hope that can help debugging the issue.

@JeroMiya Sorry but I couldn't find your email on Github.

**Comment by JeroMiya** [comment] 2016-06-27 15:33
Here is OSVR-Unreal with the updated projection code. @ccll does this look about right to you? Seems like this has fixed it. This is your "extreme" configuration above you used to demo the issue. Also, I'm using a renderOverfillFactor of 1.5 in this screenshot.

![image](https://cloud.githubusercontent.com/assets/320332/16385439/ca72bd18-3c5a-11e6-953e-c1bf1b7137b2.png)

**Comment by ccll** [comment] 2016-06-28 01:54
@JeroMiya Great! It looks correct in the screenshot, I'm curious how it looks like in the VRGate HMD.

**Comment by JeroMiya** [comment] 2016-06-28 15:55
@ccll This is now merged into OSVR-Unreal:

https://github.com/OSVR/OSVR-Unreal/pull/75

**Closed by JeroMiya** 2016-06-28 15:55 UTC
