### ISSUE TITLE
Unity anti aliasing quality setting ignored in HMD.

### ISSUE THREAD

**Issue by ChrisDenham** [sensics/OSVR-RenderManager#53] opened 2016-03-22 12:27 UTC
I'm having trouble getting the Unity anti-aliasing quality setting to affect what is shown on the HDK. It seems like the quality setting is only affecting what is displaying on the screen but not the HMD. e.g. I can up the anti-aliasing quality to x8 and it looks nice on screen, but still looks disabled on the HMD.

You can see from these screen grabs that the image used for the HMD seems unaffected by the Unity setting, but the uncorrected preview image looks much better with anti aliasing level set to x8

![image](https://cloud.githubusercontent.com/assets/2325443/13951525/68e1c4ea-f029-11e5-8ad9-d3ffaa437cec.png)

I'm running: 
Windows 8.1 64-bit 
NVidia GTX650 with driver 362.00
Unity 5.3.1f1  Personal.
OSVR Plugin for Unity 1.7
OSVR-Core-Snapshot-v0.6-1144-g9c9092f-build250-vs12-64bit
Razer HDK 1.3

**Comment by russell-taylor** [comment] 2016-03-23 13:35
I think this is related to a known issue (known to me, not yet recorded on a Github issue) with the second rendering pass.  You can work around the issue by setting the overSampling factor in the server RenderManager configuration file to be larger, which will cause more pixels to be drawn in the first pass which provides more detail for the second pass.  The issue is that this should become blur rather than aliasing even when it occurs.

Distortion correction can cause dilation of parts of the Unity image before rendering to the screen, which is a separate source of aliasing from the Unity rendering itself.

**Comment by ChrisDenham** [comment] 2016-03-23 14:25
Do you mean the "renderOverfillFactor" setting? I tried upping that from 1.5 to 5.0 but all that seemed to do was kill the framerate with no obvious improvement in aliasing effects. :-(

**Comment by russell-taylor** [comment] 2016-03-23 14:52
No, there is another one named renderOversampleFactor that is available on newer RenderManager versions that increases the rendering resolution without increasing the virtual screen size.  renderOverfillFactor increases the screen size to help keep texture clamping from happening with distortion correction and time warp.  And setting it to 5 will be rendering 25X as many pixels, so I'm sure it will kill your frame rate.

**Comment by ChrisDenham** [comment] 2016-03-23 14:59
Ah, ok thanks. I will try that. Is is supported in the current published OSVR plugin asset (v1.7) or do I need to get stuff from git hub to try it?

BTW. For what it's worth, here's results of my experiments with "renderOverfillFactor" 

![image](https://cloud.githubusercontent.com/assets/2325443/13989346/dc53000e-f107-11e5-98ad-50338aa67be4.png)

**Comment by ChrisDenham** [comment] 2016-03-23 15:19
Ah ha.. setting "renderOversampleFactor" to 2.0 has definitely reduced aliasing artifacts but seems to be quite costly to frame rate:
![image](https://cloud.githubusercontent.com/assets/2325443/13989997/96dfec28-f10a-11e5-9b9a-1d2d184c9d40.png)

**Comment by ChrisDenham** [comment] 2016-03-23 15:28
Hmmm...perhaps move the "definitely" to a "maybe" as I upped the "renderOversampleFactor" to 5.0 expecting something that looked much better, but all it did was kill the framerate (as you might expect):
![image](https://cloud.githubusercontent.com/assets/2325443/13990356/ee86e66a-f10b-11e5-8046-d6e42f8b6db5.png)

**Comment by DuFF14** [comment] 2016-03-23 20:37
I'm trying to figure out when AA from the Unity quality setting fits into the rendering pipeline. There doesn't seem to be any visual difference turning it on or off when using Rendermanager. However, using AA as an Image Effect (script attached to each VRSurface), I think there is some anti-aliasing that is visible even on the RenderManager path (lines look a little more blurry than jagged). Maybe we are asking RenderManager to Present before Unity has applied AA from the Quality setting, but after Image/Postprocess effects?

@ChrisDenham Your scene looks like a good test case, could you test with AA as an Image Effect attached to VRSurface? It is available in the Unity Standard Assets package.

Either way, there are two parts to this -- AA in Unity (quality setting or image effect), and AA in RenderManager, where aliasing is introduced by distortion correction regardless of any AA done in Unity. Is it worth doing AA in Unity at all if we always need to do it again in RenderManager?

**Comment by ChrisDenham** [comment] 2016-03-23 22:25
@DuFF14 OK, I'll try that tomorrow. That's a good point about whether its worth doing the AA in Unity, and come to think of it, maybe we want quality settings for rendering preview image to be as low as possibly to have the best chance of hitting required framerate when adding in rendering for VR stereo views, distortion and compositing etc. I suppose that's why other systems use the composed VR image for the preview mirror?

**Comment by DuFF14** [comment] 2016-03-24 03:42
The preview window will be a RenderManager feature eventually, not an extra camera in Unity. Other features have higher priority at the moment. Until then, I'd keep it off or not fullscreen if its keeping you from hitting your target framerate.

**Comment by ChrisDenham** [comment] 2016-03-24 12:18
@DuFF14  I've tried adding the Antialiasing image effect to the VRSurface and it does help a bit (the DLAA technique seems to work best) but I'm still getting nowhere near the quality I need:

![image](https://cloud.githubusercontent.com/assets/2325443/14016824/80e841ee-f1ba-11e5-908a-b778ed8af3c9.png)

**Comment by russell-taylor** [comment] 2016-03-24 12:25
An oversampling factor of 5 is indeed going to kill the frame rate (rendering 25x as many pixels).  Something like 2-3 is what I'd expect to be needed.

However, there is still an open issue in RenderManager to turn the resulting jaggies into blur when the oversampling is not sufficient.  I've looked into it a bit, but it probably has to do with the texture-blending configuration used by the shader program.

**Comment by ChrisDenham** [comment] 2016-03-24 13:22
HURRAHHH! I think I've fixed it :-) 
![image](https://cloud.githubusercontent.com/assets/2325443/14017917/9403ac66-f1c2-11e5-8ddc-4287c2cc3723.png)

The problem seems to be that the antiAliasing level needs to be set on the RenderTexture made in VREye.cs (as it defaults to 1) So to get the above result, all I had to do was hard code setting that to 8 here:
```
                        //render manager
                        if (Viewer.DisplayController.UseRenderManager)
                        {
                            surface.SetViewport(Viewer.DisplayController.RenderManager.GetEyeViewport((int)EyeIndex));

                            //create a RenderTexture for this eye's camera to render into
                            RenderTexture renderTexture = new RenderTexture(surface.Viewport.Width, surface.Viewport.Height, 24, RenderTextureFormat.Default);
							renderTexture.antiAliasing = 8;
                            surface.SetRenderTexture(renderTexture);
                        }


```

**Comment by ChrisDenham** [comment] 2016-03-24 13:25
Presumably the `renderTexture.antiAliasing` value should be inherited from the Unity Quality settings?

**Comment by DuFF14** [comment] 2016-03-24 13:41
Great find! I was under the assumption it was inheriting the quality setting. The non-hardcoded solution would be:
```C#
renderTexture.antiAliasing = QualitySettings.antiAliasing;
```
Can you open a pull request in the OSVR-Unity repo?

I think we can leave this issue open since RM distortion correction is still be adding aliasing, but hopefully this is good enough in Unity that it's less of an issue.

**Comment by ChrisDenham** [comment] 2016-03-24 13:52
@DuFF14  Ok, will do. Thanks.

**Comment by DuFF14** [comment] 2016-03-24 13:58
It actually doesn't really do much for me, testing in OSVRDemo2.unity scene and looking at the top edge of a wall. I wouldn't have noticed that it had any effect. But if it makes your more complex scene look better, that's awesome. I'll find a better test scene for AA.

**Comment by ChrisDenham** [comment] 2016-03-24 14:06
Yeah, I guess it's most noticeable light/dark boundaries of objects, Some of my scenes have tiled walls and the grout edges look really awful without AA.

**Comment by ChrisDenham** [comment] 2016-03-24 18:54
@DuFF14 just wondering if you were already using image effects or rendermanager oversampling? As that might be why you are not seeing noticable improvement with my change. Otherwise i wonder if it implies that for some reason your system does not require my change to get the AA in VR? For me, the difference is very obvious and essential. I find VR without AA is a very bad experience.

**Comment by DuFF14** [comment] 2016-03-24 21:38
Nope, I just needed a more complex scene to look at. I do see the improvement.

**Comment by russell-taylor** [comment] 2016-04-01 15:55
The Direct3D aliasing was fixed in the recent pull request, so closing this issue.

**Closed by russell-taylor** 2016-04-01 15:55 UTC
